apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: homol
spec:
  type: NodePort
  selector:
    app: apache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001  # Porta no host para acessar via localhost:30002
