apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    run: nginx
    name: nginx
    version: "1.0"
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - name: app-volume
      mountPath: /var/app
  volumes:
  - name: app-volume
    emptyDir:
      sizeLimit: "256Mi"
