############################################
# Manifesto para criar o deployment com os pods
# Autor: Bruno Salmito
# Versão: 0.1
############################################
apiVersion: v1
kind: Namespace
metadata:
  name: desenv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: desenv
  labels:
    app: nginx-deployment
    cluster: home
    versionService: "0.1"
spec:
  replicas: 2 
  selector: 
    matchLabels:
      app: nginx  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: nginx
        clusterName: home
        environment: desenvolvimento
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.2"
            memory: "64Mi"         
        ports:
        - containerPort: 80
        # Definição das probes
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:80/
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1