############################################
# Manifesto para criar o deployment com os pods
# Autor: Bruno Salmito
# Versão: 0.1
############################################
apiVersion: v1
kind: Namespace
metadata:
  name: homol

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: homol
  labels:
    app: apache-deployment
    cluster: home
    versionService: "0.1"
spec:
  replicas: 2 
  selector: 
    matchLabels:
      app: apache  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: apache
        clusterName: home
        environment: homologacao
    spec:
      containers:
      - name: apache-container
        image: httpd:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.2"
            memory: "64Mi"         
        ports:
        - containerPort: 80
        # Definição das probes

