apiVersion: v1
kind: Pod
metadata:
  name: webservers
  labels:
    name: webservers
    run: webserver
    author: Bruno
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  - name: apache
    image: httpd
    ports:
      - containerPort: 8080
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
    command: ["/bin/sh", "-c"]
    args: ["sed -i 's/Listen 80/Listen 8080/' /usr/local/apache2/conf/httpd.conf && httpd-foreground"]
