############################################
# Manifesto para criar o service para o nginx
# Autor: Bruno Salmito
# Versão: 0.1
############################################
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: desenv
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
