apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: giropops-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: giropops-senhas
spec:
  replicas: 1
  selector:
    app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
        - name: giropops-app
          image: giropops-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis
          volumeMounts:
            - name: giropops-volume
              mountPath: /volume
          resources:
            requests:
              cpu: '250m'
              memory: '16Mi'
            limits:
              cpu: '500m'
              memory: '32Mi'
      volumes:
        - name: giropops-volume
          persistentVolumeClaim:
            claimName: giropops-volume
---
apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: giropops-senhas
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: '250m'
              memory: '16Mi'
            limits:
              cpu: '500m'
              memory: '32Mi'
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
